apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: curielogger
    app.kubernetes.io/part-of: curiefense
  name: curielogger
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "9001"
    port: 9001
    targetPort: 9001
  - name: "2112"
    port: 2112
    targetPort: 2112
  selector:
    app.kubernetes.io/name: curielogger
