---
# a headless service is required for StatefulSets
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: curiefense
  name: redis-hl
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "redis-tcp"
    port: {{ .Values.global.settings.redis_port }}
    targetPort: 6379
  clusterIP: None
  selector:
    app.kubernetes.io/name: redis
