apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istiod-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    release: {{ .Release.Name }}
    app.kubernetes.io/part-of: "curiefense"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istiod-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: istiod-service-account
    namespace: {{ .Release.Namespace }}
