---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: "curiefense"
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceName: redis-hl
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: "curiefense"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - containerPort: {{ .Values.settings.port }}
            name: redis-tcp
          livenessProbe:
            tcpSocket:
              port: redis-tcp
          volumeMounts:
          - mountPath: /data
            name: persistent-redis
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      serviceAccountName: ""
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: persistent-redis
    spec:
      storageClassName: {{ .Values.storage.class }}
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.storage.size }}
