---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: confserver
    app.kubernetes.io/part-of: "curiefense"
  name: confserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: confserver
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    app.kubernetes.io/name: confserver
